### ISSUE TITLE
[Feature Requests] Monitor / Validate SSL, Monitor pages for errors/text on page, Daemon / API mode w/ callback posting after scan.

### ISSUE THREAD

**Issue by patrickcurl** [qawemlilo/ping-monitor#11]
Possible feature request, if it doesn't. 

Actually a few additions could be nice: 
1. SSL chain validation and monitoring.
2. Api/Daemon mode. Set an api-key in a config, then you can send a post request to the server: ip:port with the following payload: { key : '', urls: [array] | [url/to/files.gzip], callbackurl } 

Use case: You could deploy the daemon on multiple serverless setups to get stats around the world, and have a central db/site just call out to these satellite nodes. 
3. Monitor a page for text/data on the page, or specific criteria, easy enough for non-dynamic pages, may need headless chrome or something for react/vue vendered pages.

**Comment by qawemlilo** [comment]
@patrickcurl That is a brilliant idea! 

When I created the module I just wanted to monitor a few websites that I was managing but I have been expanding the scope recently. 

I think in the next version I will add support for API  endpoint monitoring. 

What do you think about the api below? (suggestions welcome)

```javascript
const Monitor = require('ping-monitor').apiMonitor;

const apiMonitor = new Monitor({
    url: 'https://api.ragingflame.co.za',
    interval: 10,
    httpOptions: { 
        // http options: https://nodejs.org/api/http.html#http_http_request_url_options_callback
     },
    expectedResponse: {
        statusCode: <Integer>,
        validateResponse: function(res) {
            // return true if passed 
        }
    }
});


apiMonitor.on('up', function (res, state) {
     // res <http response>
    // state <monitor state>
});


apiMonitor.on('down', function (res, state) {
     // res <http response>
    // state <monitor state>
})
```
