### ISSUE TITLE
Add POST requests support

### ISSUE THREAD

**Issue by mikedotJS** [qawemlilo/ping-monitor#12]
Hey, cool lib!

I wanted to ping some specific requests on my apps but it's not really possible at the moment as we can't add POST request body to the new Monitor instance.

We could add `POST` requests support in the monitor by adding an option `body` on `httpOptions` and use `req.write(httpOptions.body)` if the option is defined.

What do you think ?

**Comment by qawemlilo** [comment]
Hi @mikedotJS, yes that would be great. I would like to extend the lib to be as customizable as possible(without breaking the current API).

Please send a pull request if you're have worked out the solution, otherwise I'll try and implement your suggestion when I get some free time.

Thanks.

**Comment by mikedotJS** [comment]
Hey, yes i forked the repo and started working on it. I will push a pull request in the day.

Thank you.

**Comment by qawemlilo** [comment]
Thanks @mikedotJS for the pull request, I have merged, added a test and published a new version: https://www.npmjs.com/package/ping-monitor/v/0.4.3.
