### ISSUE TITLE
Can not receive down event?

### ISSUE THREAD

**Issue by tuanptit** [qawemlilo/ping-monitor#24]
Hi, I want to know when my web server is down. My code is:
```
myMonitor.on('up', function (res, state) {
  console.log('Yay!! ' + res.address + ':' + res.port + ' is up.');
}); // work fine

myMonitor.on('down', function (res, state) {
  console.log('Oh Snap!! ' + res.address + ':' + res.port + ' is down! ');
}); // not going here
```
It work fine in `up` event. But when I disable the web server to test `down `event, it not going to `down ` event
In the console show  `connect ETIMEDOUT`

**Comment by qawemlilo** [comment]
Hi @tuanptit, thank you for reporting this issue, I'll push a fix update later today.

**Comment by qawemlilo** [comment]
@tuanptit New version with fixes now available: https://www.npmjs.com/package/ping-monitor/v/0.5.0

**Comment by tuanptit** [comment]
Still not working
The console show:
```
Error: connect ETIMEDOUT 192.168.2.21:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.2.21',
  port: 80
}

```

**Comment by tuanptit** [comment]
It work now. Thanks!
