### ISSUE TITLE
HTTPS not found

### ISSUE THREAD

**Issue by ljgazzano** [qawemlilo/ping-monitor#25]
Hi, ping-monitor its a great project, but I have issues when ping https sites.
Allways return DOWN in  HTTPS sites (valid certificate and SELF SIGNED Certificate)
Exists any solution?

**Comment by qawemlilo** [comment]
Hi @ljgazzano , thank you for raising this issue. All the sites that I'm monitoring are on https. Are you using the latest version https://www.npmjs.com/package/ping-monitor/v/0.5.0? 

If you are on the latest version and still experiencing issues, please send the website url that's failing.

**Comment by ljgazzano** [comment]
const myMonitor = new Monitor({
    website: 'https://www.enargas.gob.ar/',
    title: 'Test',
    interval: 0.016 // minutes
});
--------------------------------------------------------------
I received

Monitoring:https://www.enargas.gob.ar/
Time: 2020-06-25 15:58:46

Error: write EPROTO 140555110299520:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:ssl/statem/statem_lib.c:1919:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16) {
  errno: 'EPROTO',
  code: 'EPROTO',
  syscall: 'write'
}

**Comment by qawemlilo** [comment]
@ljgazzano it looks like the website has some https errors. I will see if I can push an update to add a flag for ignoring SSL related errors.

![Screen Shot 2020-06-25 at 20 40 33](https://user-images.githubusercontent.com/363359/85779944-676b1c80-b724-11ea-92fe-da9022f8014f.png)

**Comment by ljgazzano** [comment]
if there is a possibility to ignore SSL certificates it would be great! Thank you very much, your work seems very good to me

**Comment by qawemlilo** [comment]
Hi @ljgazzano, I've been doing some research on how to handle websites with expired SSL and found the solution below.

`ping-monitor` provides an option to override or set your own `http options`. The `checkServerIdentity` property allows you to define a custom certificate validator. 

```javascript
const monitor = new Monitor({
  website: 'https://wrong.host.badssl.com',
  interval: 5,
  config: {
    intervalUnits: 'seconds'
  },
  expect: {
    statusCode: 200
  },
  httpOptions: {
    checkServerIdentity: function(host, cert) {
      return false;
    }
  }
}); 
```

I will bake in this functionality in the next release and then expose it through the config option.
