### ISSUE TITLE
How to stop an event

### ISSUE THREAD

**Issue by the94air** [qawemlilo/ping-monitor#30]
I am having an issue with stopping the monitor events after creating an instance `data.instance = new Monitor()`. The infrastructure of my application requires me to have many instances saved into an array of objects so I can detach these events once I need to. So far I tried removing the instance itself to stop the events but they are being executed even after the deletion of the instance.

```ts
data.instance = new Monitor({
  website: site.url,
  title: site.name,
  interval: site.interval,
  expect: {
    statusCode: site.statusCode
  }
});

setEvents(data.instance, site) // adding the monitor events here

monitors.push(data);
```
Here I'm trying to remove the instance to stop the events:
```ts
// looping through `monitors`

delete monitor.instance;
```
any help would be appreciated, thanks.

**Comment by qawemlilo** [comment]
Hi @the94air , I think you need to stop the monitor before removing it.

Try doing this:

```javascript
let monitor = monitors.find(monitor => monitor.instance. website === 'website url here');

monitor.instance.stop();
delete monitor.instance;
```

**Comment by the94air** [comment]
Oh, that's great. Thanks for the fast response. I have read the source code but I wasn't aware enough of how prototypes work. it's crystal clear now.
https://github.com/qawemlilo/ping-monitor/blob/master/lib/monitor.js#L171
Documenting this on the README is going to be so helpful :smile:. Thanks for help :smiley:
