### ISSUE TITLE
Moved Permanently != down

### ISSUE THREAD

**Issue by iogbole** [qawemlilo/ping-monitor#33]
This is a great project. Thanks. 
However, it treats 301, Moved Permanently as down. It shouldn't be so. 
This results in https://google.com, https//www.facebook.com etc showing as down. 

Also adding expected status 301 doesn't make any difference. 
`
 {
        url: 'https://google.com',
        interval: 1,
        expect: {
            statusCode: 301
          }
    }

`

  ` console.log(res.website + ' is down.' + res.statusMessage);`
displays `Moved Permanently`

**Comment by qawemlilo** [comment]
Hi @iogbole, thank you for raising this issue. Look out for the fix in the next package release.

**Comment by qawemlilo** [comment]
Hi @iogbole , I've done a few tests and cannot replicate the issue. The default expected status code is 200, but you can change this.

I have done a few tests using the latest version: https://www.npmjs.com/package/ping-monitor/v/0.5.2

```javascript
let mon = new Monitor({
  website: 'https://google.com',
  interval: 5,
  config: {
    intervalUnits: 'seconds'
  },
  expect: {
    statusCode: 301
  }
});

mon.on('up', function (res, state) {
  console.log('up: ', res.statusCode);
  mon.stop();
});

mon.on('down', function (res, state) {
  console.log('down: ', res.statusCode);
  mon.stop();
});

mon.on('error', function (error) {
  console.error('error: ', error);
  mon.stop();
});
```

Please let me know if you continue experiencing issues.
