### ISSUE TITLE
Process.hrtime is not a function

### ISSUE THREAD

**Issue by Silbad** [qawemlilo/ping-monitor#34]
Hello, I use ping-monitor with nuxt.js.

On local server, I have two issues

1. I have to install net module => ok (if not i have an error, perhaps add it in dependencies)
2. When I launch the server, I have this error : **Uncaught TypeError: process.hrtime is not a function** for each website.

Thanks...

**Comment by Silbad** [comment]
Ok I add browser-process-hrtime and it's ok

**Comment by qawemlilo** [comment]
Hi @Silbad , I will add browser support out of the box in the next update.
