### ISSUE TITLE
[Readme] add requirement/warning/... due to nock to ReadMe

### ISSUE THREAD

**Issue by c0ncentus** [qawemlilo/ping-monitor#39]
Hi,

![image](https://user-images.githubusercontent.com/25374826/132948817-27b1f96b-d7bc-48a1-ac25-5c689f1c6ada.png)

please warn that nodejs V9 is recommanded in the notice it would be appreciate to not have searchnig in your package json for tricky things to know.

**Comment by qawemlilo** [comment]
Hi @c0ncentus , thank you for raising this issue. I will update the docs to indicate which Node.js versions are supported.
