### ISSUE TITLE
Manually `stop` or change the `interval` on the fly for running ping monitors.

### ISSUE THREAD

**Issue by bishwo-pratap** [qawemlilo/ping-monitor#41]
Is there anyway to manually `stop` or change the `interval` => (from 15minutes to 1minute or 30 seconds) on the fly for running ping monitors?? It would be a nice addition... but if there already are such options then please do let me know.

**Comment by qawemlilo** [comment]
Hi @bishwo-pratap, I would try the code below:

```javascript
monitorInstance.pause();
monitorInstance.interval = // new interval 
monitorInstance.resume();
```

Please let me know if you run into any issues (I have not run any tests for this use case).

**Comment by bishwo-pratap** [comment]
OHK!!! will let you know how this goes!!
