### ISSUE TITLE
Hmm

### ISSUE THREAD

**Issue by ThisMe124** [qawemlilo/ping-monitor#42]
Support for notif website Down/Up??

**Comment by qawemlilo** [comment]
@ThisMe124 any suggestions on how that would work?

**Comment by ThisMe124** [comment]
> 

I found more package

**Comment by ThisMe124** [comment]
Meybe i close issue

**Comment by ThisMe124** [comment]
> @ThisMe124 any suggestions on how that would wor

> @ThisMe124 any suggestions on how that would work?

and I Found a Package named status-monitor maybe you can reference from that package...

**Comment by ThisMe124** [comment]
But http only :(

**Comment by kailashvele** [comment]
I have added Slack Notification on the down, timeout and error events.

**Comment by ThisMe124** [comment]
> I have added Slack Notification on the down, timeout and error events.

Can notified on the up?

**Comment by qawemlilo** [comment]
@ThisMe124 Yes.

@kailashvele created a Slack Notification channel here: https://github.com/qawemlilo/ping-monitor-channels/blob/main/channels/Slack.js

You can edit the `up` method to send your notifications.

**Comment by ThisMe124** [comment]
> @ThisMe124 Yes.
> 
> @kailashvele created a Slack Notification channel here: https://github.com/qawemlilo/ping-monitor-channels/blob/main/channels/Slack.js
> 
> You can edit the `up` method to send your notifications.

But response spam

**Comment by qawemlilo** [comment]
> > @ThisMe124 Yes.
> > @kailashvele created a Slack Notification channel here: https://github.com/qawemlilo/ping-monitor-channels/blob/main/channels/Slack.js
> > You can edit the `up` method to send your notifications.
> 
> But response spam

This is how I would try and do it (I have not test this):

```javascript
const Monitor = require('ping-monitor');

const apiMonitor = new Monitor({
    website: 'http://api.myapp.com',
    title: 'My API',
    interval: 10000, // 10 seconds

    config: {
      intervalUnits: 'milliseconds'
    }
});

apiMonitor.on('up', function(response, state) {
    let now = Date.now();
    let oneRequestAgo = (10000 * 2) - 10;
 
    // if the api was down 1 request ago 
    if(now - state.lastDownTime < oneRequestAgo) {
       // notify me on slack
    }

   // otherwise ignore
});
```

**Comment by ThisMe124** [comment]
> > > @ThisMe124 Yes.
> > > @kailashvele created a Slack Notification channel here: https://github.com/qawemlilo/ping-monitor-channels/blob/main/channels/Slack.js
> > > You can edit the `up` method to send your notifications.
> > 
> > 
> > But response spam
> 
> This is how I would try and do it (I have not test this):
> 
> ```js
> const Monitor = require('ping-monitor');
> 
> const apiMonitor = new Monitor({
>     website: 'http://api.myapp.com',
>     title: 'My API',
>     interval: 10000, // 10 seconds
> 
>     config: {
>       intervalUnits: 'milliseconds'
>     }
> });
> 
> apiMonitor.on('up', function(response, state) {
>     let now = Date.now();
>     let oneRequestAgo = (10000 * 2) - 10;
>  
>     // if the api was down 1 request ago 
>     if((now - state.lastDownTime) < oneRequestAgo) {
>        // notify me on slack
>     }
> 
>    // otherwise ignore
> });
> ```

This is only up how on is down? down requests is spam response

**Comment by ThisMe124** [comment]
> 

Can only ip address and port?

**Comment by ThisMe124** [comment]
> @ThisMe124 there's a new event that is fired once when a server is up after download time.
> 
> ```js
>   const ping = new Monitor({
>     address: '34.22.237.1',
>     port: 1234,
>     interval: 10
>   });
> 
>   ping.on('up', function (res, state) {
>     console.log('Yay!! Service is up');
>   });
> 
>   ping.on('down', function (res, state) {
>     console.log(':( Service is down!');
>   });
> 
>   ping.on('restored', function (res, state) {
>     console.log('Yay!! Service has been restored');
>   });
> 
>   ping.on('error', function (error, res) {
>     console.error(error);
>   });
> ```
> 
> Also, have a look at the `threshold` feature added in v0.8.1: https://www.npmjs.com/package/ping-monitor#v081
> 
> Hope that helps.

Emm can you give me exams how to use that?

**Comment by qawemlilo** [comment]
> that

You can find the example on this link: https://www.npmjs.com/package/ping-monitor#threshold-example

**Comment by ThisMe124** [comment]
> > that
> 
> You can find the example on this link: https://www.npmjs.com/package/ping-monitor#threshold-example

This event "up" Not spam response?

**Comment by ThisMe124** [comment]
@ThisMe124 there's a new event that is fired once when a server is up after download time.

```js
  const ping = new Monitor({
    address: '34.22.237.1',
    port: 1234,
    interval: 10
  });

  ping.on('up', function (res, state) {
    console.log('Yay!! Service is up');
  });

  ping.on('down', function (res, state) {
    console.log(':( Service is down!');
  });

  ping.on('restored', function (res, state) {
    console.log('Yay!! Service has been restored');
  });

  ping.on('error', function (error, res) {
    console.error(error);
  });
```

Also, have a look at the `threshold` feature added in v0.8.1: https://www.npmjs.com/package/ping-monitor#v081

Hope that helps.

Isn't it possible to send it once every time there is an up, error, or down on the website being checked?

**Comment by ThisMe124** [comment]
> @ThisMe124 there's a new event that is fired once when a server is up after download time.
> 
> ```js
>   const ping = new Monitor({
>     address: '34.22.237.1',
>     port: 1234,
>     interval: 10
>   });
> 
>   ping.on('up', function (res, state) {
>     console.log('Yay!! Service is up');
>   });
> 
>   ping.on('down', function (res, state) {
>     console.log(':( Service is down!');
>   });
> 
>   ping.on('restored', function (res, state) {
>     console.log('Yay!! Service has been restored');
>   });
> 
>   ping.on('error', function (error, res) {
>     console.error(error);
>   });
> ```
> 
> Also, have a look at the `threshold` feature added in v0.8.1: https://www.npmjs.com/package/ping-monitor#v081
> 
> Hope that helps.

Isn't it possible to send it once every time there is an up, error, or down on the website being checked? , without spam
