### ISSUE TITLE
Typings required in TypeScript progress

### ISSUE THREAD

**Issue by r1zyn** [qawemlilo/ping-monitor#46]
Can you add typings for this library since I'm using this in a TypeScript project

**Comment by qawemlilo** [comment]
Hi @unkn0wnF, this package is currently written in JavaScript, adding typings would mean that I have to rewrite it in TypeScript (which I don't have much experience with). The best option is to fork the repo and convert it to TypeScript.

**Comment by pbombnz** [comment]
I forked this project awhile back to create [availability-monitor](https://github.com/pbombnz/availability-monitor) for us TypeScript people. Its a little different but does the job. Disclaimer though, I don't update it regularly, so it might not be as stable as @qawemlilo 's ping-monitor.

**Comment by qawemlilo** [comment]
@pbombnz That's great! I will have a look and possibly contribute to improve my TypeScript.

**Comment by unkn0wnF** [comment]
> Hi @unkn0wnF, this package is currently written in JavaScript, adding typings would mean that I have to rewrite it in TypeScript (which I don't have much experience with). The best option is to fork the repo and convert it to TypeScript.

You don't have to rewrite it in TS, I just added a typings file and put it inside the lib folder and it fixed the problem, although not sure whether it's accurate

**Comment by unkn0wnF** [comment]
> I forked this project awhile back to create [availability-monitor](https://github.com/pbombnz/availability-monitor) for us TypeScript people. Its a little different but does the job. Disclaimer though, I don't update it regularly, so it might not be as stable as @qawemlilo 's ping-monitor.

Cool, I'll check it out
